library(shiny)
library(bslib)
library(rlang)
library(curl)
library(reshape2)
library(thematic)
library(bsicons)
library(ggridges)
library(sf)
library(geobr)
library(leaflet)   # Mapa interativo
library(ggplot2)   # Para paleta de cores
library(tidyverse)
library(data.table)
library(ribge)
library(shinycssloaders)
library(patchwork)
library(gridExtra)
library(DT)
